networks:
  store-suite:
    external: true

services:

  store:
    image: civi-store:1.0.0
    environment:
      DB_URL: jdbc:mariadb://db:3306/order_service
      DB_USER: root
      DB_PASSWORD: rootpassword
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "9000:9000"
    networks:
      - store-suite