# Server Properties
server:
  port: 9000
  servlet:
    context-path: /store

#logging
logging:
  info:
    path: ./target/log
    name: info
  error:
    path: ./target/log
    name: error

# Swagger activation
springdoc:
  api-docs:
    enabled: true
    path: /swagger-ui/v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

# Spring Jpa
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/order_service
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MariaDBDialect
  data:
    redis:
      host: localhost
      port: 6379
      lock:
        wait-time: 3
        lease-time: 5